-- Schema para o Sticker Tracker (Supabase / Postgres)

-- Tabela com o catálogo fixo de todas as figurinhas
create table if not exists stickers (
  code text primary key,
  team_name text not null,
  group_label text not null,
  category text not null check (category in ('team','special','coke')),
  position int not null
);

-- Tabela de progresso por usuário (uma linha por figurinha marcada)
create table if not exists user_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  sticker_code text not null references stickers(code) on delete cascade,
  owned boolean not null default true,
  duplicates integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, sticker_code)
);

-- Habilita Row Level Security
alter table user_progress enable row level security;
alter table stickers enable row level security;

-- Qualquer usuário autenticado pode ler o catálogo de figurinhas
create policy "stickers are readable by authenticated users"
  on stickers for select
  to authenticated
  using (true);

-- Cada usuário só vê/edita o próprio progresso
create policy "users manage their own progress"
  on user_progress for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Histórico de eventos (marcações, trocas, aberturas de envelope, etc.)
create table if not exists history_events (
  id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (id, user_id)
);

alter table history_events enable row level security;

-- Cada usuário só vê/edita o próprio histórico
create policy "users manage their own history"
  on history_events for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Seed do catálogo (994 figurinhas: 48 times x20 + 20 especiais + 14 Coca-Cola)
insert into stickers (code, team_name, group_label, category, position) values
  ('MEX1', 'México', 'A', 'team', 1),
  ('MEX2', 'México', 'A', 'team', 2),
  ('MEX3', 'México', 'A', 'team', 3),
  ('MEX4', 'México', 'A', 'team', 4),
  ('MEX5', 'México', 'A', 'team', 5),
  ('MEX6', 'México', 'A', 'team', 6),
  ('MEX7', 'México', 'A', 'team', 7),
  ('MEX8', 'México', 'A', 'team', 8),
  ('MEX9', 'México', 'A', 'team', 9),
  ('MEX10', 'México', 'A', 'team', 10),
  ('MEX11', 'México', 'A', 'team', 11),
  ('MEX12', 'México', 'A', 'team', 12),
  ('MEX13', 'México', 'A', 'team', 13),
  ('MEX14', 'México', 'A', 'team', 14),
  ('MEX15', 'México', 'A', 'team', 15),
  ('MEX16', 'México', 'A', 'team', 16),
  ('MEX17', 'México', 'A', 'team', 17),
  ('MEX18', 'México', 'A', 'team', 18),
  ('MEX19', 'México', 'A', 'team', 19),
  ('MEX20', 'México', 'A', 'team', 20),
  ('RSA1', 'África do Sul', 'A', 'team', 1),
  ('RSA2', 'África do Sul', 'A', 'team', 2),
  ('RSA3', 'África do Sul', 'A', 'team', 3),
  ('RSA4', 'África do Sul', 'A', 'team', 4),
  ('RSA5', 'África do Sul', 'A', 'team', 5),
  ('RSA6', 'África do Sul', 'A', 'team', 6),
  ('RSA7', 'África do Sul', 'A', 'team', 7),
  ('RSA8', 'África do Sul', 'A', 'team', 8),
  ('RSA9', 'África do Sul', 'A', 'team', 9),
  ('RSA10', 'África do Sul', 'A', 'team', 10),
  ('RSA11', 'África do Sul', 'A', 'team', 11),
  ('RSA12', 'África do Sul', 'A', 'team', 12),
  ('RSA13', 'África do Sul', 'A', 'team', 13),
  ('RSA14', 'África do Sul', 'A', 'team', 14),
  ('RSA15', 'África do Sul', 'A', 'team', 15),
  ('RSA16', 'África do Sul', 'A', 'team', 16),
  ('RSA17', 'África do Sul', 'A', 'team', 17),
  ('RSA18', 'África do Sul', 'A', 'team', 18),
  ('RSA19', 'África do Sul', 'A', 'team', 19),
  ('RSA20', 'África do Sul', 'A', 'team', 20),
  ('KOR1', 'Coreia do Sul', 'A', 'team', 1),
  ('KOR2', 'Coreia do Sul', 'A', 'team', 2),
  ('KOR3', 'Coreia do Sul', 'A', 'team', 3),
  ('KOR4', 'Coreia do Sul', 'A', 'team', 4),
  ('KOR5', 'Coreia do Sul', 'A', 'team', 5),
  ('KOR6', 'Coreia do Sul', 'A', 'team', 6),
  ('KOR7', 'Coreia do Sul', 'A', 'team', 7),
  ('KOR8', 'Coreia do Sul', 'A', 'team', 8),
  ('KOR9', 'Coreia do Sul', 'A', 'team', 9),
  ('KOR10', 'Coreia do Sul', 'A', 'team', 10),
  ('KOR11', 'Coreia do Sul', 'A', 'team', 11),
  ('KOR12', 'Coreia do Sul', 'A', 'team', 12),
  ('KOR13', 'Coreia do Sul', 'A', 'team', 13),
  ('KOR14', 'Coreia do Sul', 'A', 'team', 14),
  ('KOR15', 'Coreia do Sul', 'A', 'team', 15),
  ('KOR16', 'Coreia do Sul', 'A', 'team', 16),
  ('KOR17', 'Coreia do Sul', 'A', 'team', 17),
  ('KOR18', 'Coreia do Sul', 'A', 'team', 18),
  ('KOR19', 'Coreia do Sul', 'A', 'team', 19),
  ('KOR20', 'Coreia do Sul', 'A', 'team', 20),
  ('CZE1', 'Rep. Tcheca', 'A', 'team', 1),
  ('CZE2', 'Rep. Tcheca', 'A', 'team', 2),
  ('CZE3', 'Rep. Tcheca', 'A', 'team', 3),
  ('CZE4', 'Rep. Tcheca', 'A', 'team', 4),
  ('CZE5', 'Rep. Tcheca', 'A', 'team', 5),
  ('CZE6', 'Rep. Tcheca', 'A', 'team', 6),
  ('CZE7', 'Rep. Tcheca', 'A', 'team', 7),
  ('CZE8', 'Rep. Tcheca', 'A', 'team', 8),
  ('CZE9', 'Rep. Tcheca', 'A', 'team', 9),
  ('CZE10', 'Rep. Tcheca', 'A', 'team', 10),
  ('CZE11', 'Rep. Tcheca', 'A', 'team', 11),
  ('CZE12', 'Rep. Tcheca', 'A', 'team', 12),
  ('CZE13', 'Rep. Tcheca', 'A', 'team', 13),
  ('CZE14', 'Rep. Tcheca', 'A', 'team', 14),
  ('CZE15', 'Rep. Tcheca', 'A', 'team', 15),
  ('CZE16', 'Rep. Tcheca', 'A', 'team', 16),
  ('CZE17', 'Rep. Tcheca', 'A', 'team', 17),
  ('CZE18', 'Rep. Tcheca', 'A', 'team', 18),
  ('CZE19', 'Rep. Tcheca', 'A', 'team', 19),
  ('CZE20', 'Rep. Tcheca', 'A', 'team', 20),
  ('CAN1', 'Canadá', 'B', 'team', 1),
  ('CAN2', 'Canadá', 'B', 'team', 2),
  ('CAN3', 'Canadá', 'B', 'team', 3),
  ('CAN4', 'Canadá', 'B', 'team', 4),
  ('CAN5', 'Canadá', 'B', 'team', 5),
  ('CAN6', 'Canadá', 'B', 'team', 6),
  ('CAN7', 'Canadá', 'B', 'team', 7),
  ('CAN8', 'Canadá', 'B', 'team', 8),
  ('CAN9', 'Canadá', 'B', 'team', 9),
  ('CAN10', 'Canadá', 'B', 'team', 10),
  ('CAN11', 'Canadá', 'B', 'team', 11),
  ('CAN12', 'Canadá', 'B', 'team', 12),
  ('CAN13', 'Canadá', 'B', 'team', 13),
  ('CAN14', 'Canadá', 'B', 'team', 14),
  ('CAN15', 'Canadá', 'B', 'team', 15),
  ('CAN16', 'Canadá', 'B', 'team', 16),
  ('CAN17', 'Canadá', 'B', 'team', 17),
  ('CAN18', 'Canadá', 'B', 'team', 18),
  ('CAN19', 'Canadá', 'B', 'team', 19),
  ('CAN20', 'Canadá', 'B', 'team', 20),
  ('BIH1', 'Bósnia', 'B', 'team', 1),
  ('BIH2', 'Bósnia', 'B', 'team', 2),
  ('BIH3', 'Bósnia', 'B', 'team', 3),
  ('BIH4', 'Bósnia', 'B', 'team', 4),
  ('BIH5', 'Bósnia', 'B', 'team', 5),
  ('BIH6', 'Bósnia', 'B', 'team', 6),
  ('BIH7', 'Bósnia', 'B', 'team', 7),
  ('BIH8', 'Bósnia', 'B', 'team', 8),
  ('BIH9', 'Bósnia', 'B', 'team', 9),
  ('BIH10', 'Bósnia', 'B', 'team', 10),
  ('BIH11', 'Bósnia', 'B', 'team', 11),
  ('BIH12', 'Bósnia', 'B', 'team', 12),
  ('BIH13', 'Bósnia', 'B', 'team', 13),
  ('BIH14', 'Bósnia', 'B', 'team', 14),
  ('BIH15', 'Bósnia', 'B', 'team', 15),
  ('BIH16', 'Bósnia', 'B', 'team', 16),
  ('BIH17', 'Bósnia', 'B', 'team', 17),
  ('BIH18', 'Bósnia', 'B', 'team', 18),
  ('BIH19', 'Bósnia', 'B', 'team', 19),
  ('BIH20', 'Bósnia', 'B', 'team', 20),
  ('QAT1', 'Catar', 'B', 'team', 1),
  ('QAT2', 'Catar', 'B', 'team', 2),
  ('QAT3', 'Catar', 'B', 'team', 3),
  ('QAT4', 'Catar', 'B', 'team', 4),
  ('QAT5', 'Catar', 'B', 'team', 5),
  ('QAT6', 'Catar', 'B', 'team', 6),
  ('QAT7', 'Catar', 'B', 'team', 7),
  ('QAT8', 'Catar', 'B', 'team', 8),
  ('QAT9', 'Catar', 'B', 'team', 9),
  ('QAT10', 'Catar', 'B', 'team', 10),
  ('QAT11', 'Catar', 'B', 'team', 11),
  ('QAT12', 'Catar', 'B', 'team', 12),
  ('QAT13', 'Catar', 'B', 'team', 13),
  ('QAT14', 'Catar', 'B', 'team', 14),
  ('QAT15', 'Catar', 'B', 'team', 15),
  ('QAT16', 'Catar', 'B', 'team', 16),
  ('QAT17', 'Catar', 'B', 'team', 17),
  ('QAT18', 'Catar', 'B', 'team', 18),
  ('QAT19', 'Catar', 'B', 'team', 19),
  ('QAT20', 'Catar', 'B', 'team', 20),
  ('SUI1', 'Suíça', 'B', 'team', 1),
  ('SUI2', 'Suíça', 'B', 'team', 2),
  ('SUI3', 'Suíça', 'B', 'team', 3),
  ('SUI4', 'Suíça', 'B', 'team', 4),
  ('SUI5', 'Suíça', 'B', 'team', 5),
  ('SUI6', 'Suíça', 'B', 'team', 6),
  ('SUI7', 'Suíça', 'B', 'team', 7),
  ('SUI8', 'Suíça', 'B', 'team', 8),
  ('SUI9', 'Suíça', 'B', 'team', 9),
  ('SUI10', 'Suíça', 'B', 'team', 10),
  ('SUI11', 'Suíça', 'B', 'team', 11),
  ('SUI12', 'Suíça', 'B', 'team', 12),
  ('SUI13', 'Suíça', 'B', 'team', 13),
  ('SUI14', 'Suíça', 'B', 'team', 14),
  ('SUI15', 'Suíça', 'B', 'team', 15),
  ('SUI16', 'Suíça', 'B', 'team', 16),
  ('SUI17', 'Suíça', 'B', 'team', 17),
  ('SUI18', 'Suíça', 'B', 'team', 18),
  ('SUI19', 'Suíça', 'B', 'team', 19),
  ('SUI20', 'Suíça', 'B', 'team', 20),
  ('BRA1', 'Brasil', 'C', 'team', 1),
  ('BRA2', 'Brasil', 'C', 'team', 2),
  ('BRA3', 'Brasil', 'C', 'team', 3),
  ('BRA4', 'Brasil', 'C', 'team', 4),
  ('BRA5', 'Brasil', 'C', 'team', 5),
  ('BRA6', 'Brasil', 'C', 'team', 6),
  ('BRA7', 'Brasil', 'C', 'team', 7),
  ('BRA8', 'Brasil', 'C', 'team', 8),
  ('BRA9', 'Brasil', 'C', 'team', 9),
  ('BRA10', 'Brasil', 'C', 'team', 10),
  ('BRA11', 'Brasil', 'C', 'team', 11),
  ('BRA12', 'Brasil', 'C', 'team', 12),
  ('BRA13', 'Brasil', 'C', 'team', 13),
  ('BRA14', 'Brasil', 'C', 'team', 14),
  ('BRA15', 'Brasil', 'C', 'team', 15),
  ('BRA16', 'Brasil', 'C', 'team', 16),
  ('BRA17', 'Brasil', 'C', 'team', 17),
  ('BRA18', 'Brasil', 'C', 'team', 18),
  ('BRA19', 'Brasil', 'C', 'team', 19),
  ('BRA20', 'Brasil', 'C', 'team', 20),
  ('MAR1', 'Marrocos', 'C', 'team', 1),
  ('MAR2', 'Marrocos', 'C', 'team', 2),
  ('MAR3', 'Marrocos', 'C', 'team', 3),
  ('MAR4', 'Marrocos', 'C', 'team', 4),
  ('MAR5', 'Marrocos', 'C', 'team', 5),
  ('MAR6', 'Marrocos', 'C', 'team', 6),
  ('MAR7', 'Marrocos', 'C', 'team', 7),
  ('MAR8', 'Marrocos', 'C', 'team', 8),
  ('MAR9', 'Marrocos', 'C', 'team', 9),
  ('MAR10', 'Marrocos', 'C', 'team', 10),
  ('MAR11', 'Marrocos', 'C', 'team', 11),
  ('MAR12', 'Marrocos', 'C', 'team', 12),
  ('MAR13', 'Marrocos', 'C', 'team', 13),
  ('MAR14', 'Marrocos', 'C', 'team', 14),
  ('MAR15', 'Marrocos', 'C', 'team', 15),
  ('MAR16', 'Marrocos', 'C', 'team', 16),
  ('MAR17', 'Marrocos', 'C', 'team', 17),
  ('MAR18', 'Marrocos', 'C', 'team', 18),
  ('MAR19', 'Marrocos', 'C', 'team', 19),
  ('MAR20', 'Marrocos', 'C', 'team', 20),
  ('HAI1', 'Haiti', 'C', 'team', 1),
  ('HAI2', 'Haiti', 'C', 'team', 2),
  ('HAI3', 'Haiti', 'C', 'team', 3),
  ('HAI4', 'Haiti', 'C', 'team', 4),
  ('HAI5', 'Haiti', 'C', 'team', 5),
  ('HAI6', 'Haiti', 'C', 'team', 6),
  ('HAI7', 'Haiti', 'C', 'team', 7),
  ('HAI8', 'Haiti', 'C', 'team', 8),
  ('HAI9', 'Haiti', 'C', 'team', 9),
  ('HAI10', 'Haiti', 'C', 'team', 10),
  ('HAI11', 'Haiti', 'C', 'team', 11),
  ('HAI12', 'Haiti', 'C', 'team', 12),
  ('HAI13', 'Haiti', 'C', 'team', 13),
  ('HAI14', 'Haiti', 'C', 'team', 14),
  ('HAI15', 'Haiti', 'C', 'team', 15),
  ('HAI16', 'Haiti', 'C', 'team', 16),
  ('HAI17', 'Haiti', 'C', 'team', 17),
  ('HAI18', 'Haiti', 'C', 'team', 18),
  ('HAI19', 'Haiti', 'C', 'team', 19),
  ('HAI20', 'Haiti', 'C', 'team', 20),
  ('SCO1', 'Escócia', 'C', 'team', 1),
  ('SCO2', 'Escócia', 'C', 'team', 2),
  ('SCO3', 'Escócia', 'C', 'team', 3),
  ('SCO4', 'Escócia', 'C', 'team', 4),
  ('SCO5', 'Escócia', 'C', 'team', 5),
  ('SCO6', 'Escócia', 'C', 'team', 6),
  ('SCO7', 'Escócia', 'C', 'team', 7),
  ('SCO8', 'Escócia', 'C', 'team', 8),
  ('SCO9', 'Escócia', 'C', 'team', 9),
  ('SCO10', 'Escócia', 'C', 'team', 10),
  ('SCO11', 'Escócia', 'C', 'team', 11),
  ('SCO12', 'Escócia', 'C', 'team', 12),
  ('SCO13', 'Escócia', 'C', 'team', 13),
  ('SCO14', 'Escócia', 'C', 'team', 14),
  ('SCO15', 'Escócia', 'C', 'team', 15),
  ('SCO16', 'Escócia', 'C', 'team', 16),
  ('SCO17', 'Escócia', 'C', 'team', 17),
  ('SCO18', 'Escócia', 'C', 'team', 18),
  ('SCO19', 'Escócia', 'C', 'team', 19),
  ('SCO20', 'Escócia', 'C', 'team', 20),
  ('USA1', 'Estados Unidos', 'D', 'team', 1),
  ('USA2', 'Estados Unidos', 'D', 'team', 2),
  ('USA3', 'Estados Unidos', 'D', 'team', 3),
  ('USA4', 'Estados Unidos', 'D', 'team', 4),
  ('USA5', 'Estados Unidos', 'D', 'team', 5),
  ('USA6', 'Estados Unidos', 'D', 'team', 6),
  ('USA7', 'Estados Unidos', 'D', 'team', 7),
  ('USA8', 'Estados Unidos', 'D', 'team', 8),
  ('USA9', 'Estados Unidos', 'D', 'team', 9),
  ('USA10', 'Estados Unidos', 'D', 'team', 10),
  ('USA11', 'Estados Unidos', 'D', 'team', 11),
  ('USA12', 'Estados Unidos', 'D', 'team', 12),
  ('USA13', 'Estados Unidos', 'D', 'team', 13),
  ('USA14', 'Estados Unidos', 'D', 'team', 14),
  ('USA15', 'Estados Unidos', 'D', 'team', 15),
  ('USA16', 'Estados Unidos', 'D', 'team', 16),
  ('USA17', 'Estados Unidos', 'D', 'team', 17),
  ('USA18', 'Estados Unidos', 'D', 'team', 18),
  ('USA19', 'Estados Unidos', 'D', 'team', 19),
  ('USA20', 'Estados Unidos', 'D', 'team', 20),
  ('PAR1', 'Paraguai', 'D', 'team', 1),
  ('PAR2', 'Paraguai', 'D', 'team', 2),
  ('PAR3', 'Paraguai', 'D', 'team', 3),
  ('PAR4', 'Paraguai', 'D', 'team', 4),
  ('PAR5', 'Paraguai', 'D', 'team', 5),
  ('PAR6', 'Paraguai', 'D', 'team', 6),
  ('PAR7', 'Paraguai', 'D', 'team', 7),
  ('PAR8', 'Paraguai', 'D', 'team', 8),
  ('PAR9', 'Paraguai', 'D', 'team', 9),
  ('PAR10', 'Paraguai', 'D', 'team', 10),
  ('PAR11', 'Paraguai', 'D', 'team', 11),
  ('PAR12', 'Paraguai', 'D', 'team', 12),
  ('PAR13', 'Paraguai', 'D', 'team', 13),
  ('PAR14', 'Paraguai', 'D', 'team', 14),
  ('PAR15', 'Paraguai', 'D', 'team', 15),
  ('PAR16', 'Paraguai', 'D', 'team', 16),
  ('PAR17', 'Paraguai', 'D', 'team', 17),
  ('PAR18', 'Paraguai', 'D', 'team', 18),
  ('PAR19', 'Paraguai', 'D', 'team', 19),
  ('PAR20', 'Paraguai', 'D', 'team', 20),
  ('AUS1', 'Austrália', 'D', 'team', 1),
  ('AUS2', 'Austrália', 'D', 'team', 2),
  ('AUS3', 'Austrália', 'D', 'team', 3),
  ('AUS4', 'Austrália', 'D', 'team', 4),
  ('AUS5', 'Austrália', 'D', 'team', 5),
  ('AUS6', 'Austrália', 'D', 'team', 6),
  ('AUS7', 'Austrália', 'D', 'team', 7),
  ('AUS8', 'Austrália', 'D', 'team', 8),
  ('AUS9', 'Austrália', 'D', 'team', 9),
  ('AUS10', 'Austrália', 'D', 'team', 10),
  ('AUS11', 'Austrália', 'D', 'team', 11),
  ('AUS12', 'Austrália', 'D', 'team', 12),
  ('AUS13', 'Austrália', 'D', 'team', 13),
  ('AUS14', 'Austrália', 'D', 'team', 14),
  ('AUS15', 'Austrália', 'D', 'team', 15),
  ('AUS16', 'Austrália', 'D', 'team', 16),
  ('AUS17', 'Austrália', 'D', 'team', 17),
  ('AUS18', 'Austrália', 'D', 'team', 18),
  ('AUS19', 'Austrália', 'D', 'team', 19),
  ('AUS20', 'Austrália', 'D', 'team', 20),
  ('TUR1', 'Turquia', 'D', 'team', 1),
  ('TUR2', 'Turquia', 'D', 'team', 2),
  ('TUR3', 'Turquia', 'D', 'team', 3),
  ('TUR4', 'Turquia', 'D', 'team', 4),
  ('TUR5', 'Turquia', 'D', 'team', 5),
  ('TUR6', 'Turquia', 'D', 'team', 6),
  ('TUR7', 'Turquia', 'D', 'team', 7),
  ('TUR8', 'Turquia', 'D', 'team', 8),
  ('TUR9', 'Turquia', 'D', 'team', 9),
  ('TUR10', 'Turquia', 'D', 'team', 10),
  ('TUR11', 'Turquia', 'D', 'team', 11),
  ('TUR12', 'Turquia', 'D', 'team', 12),
  ('TUR13', 'Turquia', 'D', 'team', 13),
  ('TUR14', 'Turquia', 'D', 'team', 14),
  ('TUR15', 'Turquia', 'D', 'team', 15),
  ('TUR16', 'Turquia', 'D', 'team', 16),
  ('TUR17', 'Turquia', 'D', 'team', 17),
  ('TUR18', 'Turquia', 'D', 'team', 18),
  ('TUR19', 'Turquia', 'D', 'team', 19),
  ('TUR20', 'Turquia', 'D', 'team', 20),
  ('GER1', 'Alemanha', 'E', 'team', 1),
  ('GER2', 'Alemanha', 'E', 'team', 2),
  ('GER3', 'Alemanha', 'E', 'team', 3),
  ('GER4', 'Alemanha', 'E', 'team', 4),
  ('GER5', 'Alemanha', 'E', 'team', 5),
  ('GER6', 'Alemanha', 'E', 'team', 6),
  ('GER7', 'Alemanha', 'E', 'team', 7),
  ('GER8', 'Alemanha', 'E', 'team', 8),
  ('GER9', 'Alemanha', 'E', 'team', 9),
  ('GER10', 'Alemanha', 'E', 'team', 10),
  ('GER11', 'Alemanha', 'E', 'team', 11),
  ('GER12', 'Alemanha', 'E', 'team', 12),
  ('GER13', 'Alemanha', 'E', 'team', 13),
  ('GER14', 'Alemanha', 'E', 'team', 14),
  ('GER15', 'Alemanha', 'E', 'team', 15),
  ('GER16', 'Alemanha', 'E', 'team', 16),
  ('GER17', 'Alemanha', 'E', 'team', 17),
  ('GER18', 'Alemanha', 'E', 'team', 18),
  ('GER19', 'Alemanha', 'E', 'team', 19),
  ('GER20', 'Alemanha', 'E', 'team', 20),
  ('CUW1', 'Curaçao', 'E', 'team', 1),
  ('CUW2', 'Curaçao', 'E', 'team', 2),
  ('CUW3', 'Curaçao', 'E', 'team', 3),
  ('CUW4', 'Curaçao', 'E', 'team', 4),
  ('CUW5', 'Curaçao', 'E', 'team', 5),
  ('CUW6', 'Curaçao', 'E', 'team', 6),
  ('CUW7', 'Curaçao', 'E', 'team', 7),
  ('CUW8', 'Curaçao', 'E', 'team', 8),
  ('CUW9', 'Curaçao', 'E', 'team', 9),
  ('CUW10', 'Curaçao', 'E', 'team', 10),
  ('CUW11', 'Curaçao', 'E', 'team', 11),
  ('CUW12', 'Curaçao', 'E', 'team', 12),
  ('CUW13', 'Curaçao', 'E', 'team', 13),
  ('CUW14', 'Curaçao', 'E', 'team', 14),
  ('CUW15', 'Curaçao', 'E', 'team', 15),
  ('CUW16', 'Curaçao', 'E', 'team', 16),
  ('CUW17', 'Curaçao', 'E', 'team', 17),
  ('CUW18', 'Curaçao', 'E', 'team', 18),
  ('CUW19', 'Curaçao', 'E', 'team', 19),
  ('CUW20', 'Curaçao', 'E', 'team', 20),
  ('CIV1', 'Costa do Marfim', 'E', 'team', 1),
  ('CIV2', 'Costa do Marfim', 'E', 'team', 2),
  ('CIV3', 'Costa do Marfim', 'E', 'team', 3),
  ('CIV4', 'Costa do Marfim', 'E', 'team', 4),
  ('CIV5', 'Costa do Marfim', 'E', 'team', 5),
  ('CIV6', 'Costa do Marfim', 'E', 'team', 6),
  ('CIV7', 'Costa do Marfim', 'E', 'team', 7),
  ('CIV8', 'Costa do Marfim', 'E', 'team', 8),
  ('CIV9', 'Costa do Marfim', 'E', 'team', 9),
  ('CIV10', 'Costa do Marfim', 'E', 'team', 10),
  ('CIV11', 'Costa do Marfim', 'E', 'team', 11),
  ('CIV12', 'Costa do Marfim', 'E', 'team', 12),
  ('CIV13', 'Costa do Marfim', 'E', 'team', 13),
  ('CIV14', 'Costa do Marfim', 'E', 'team', 14),
  ('CIV15', 'Costa do Marfim', 'E', 'team', 15),
  ('CIV16', 'Costa do Marfim', 'E', 'team', 16),
  ('CIV17', 'Costa do Marfim', 'E', 'team', 17),
  ('CIV18', 'Costa do Marfim', 'E', 'team', 18),
  ('CIV19', 'Costa do Marfim', 'E', 'team', 19),
  ('CIV20', 'Costa do Marfim', 'E', 'team', 20),
  ('ECU1', 'Equador', 'E', 'team', 1),
  ('ECU2', 'Equador', 'E', 'team', 2),
  ('ECU3', 'Equador', 'E', 'team', 3),
  ('ECU4', 'Equador', 'E', 'team', 4),
  ('ECU5', 'Equador', 'E', 'team', 5),
  ('ECU6', 'Equador', 'E', 'team', 6),
  ('ECU7', 'Equador', 'E', 'team', 7),
  ('ECU8', 'Equador', 'E', 'team', 8),
  ('ECU9', 'Equador', 'E', 'team', 9),
  ('ECU10', 'Equador', 'E', 'team', 10),
  ('ECU11', 'Equador', 'E', 'team', 11),
  ('ECU12', 'Equador', 'E', 'team', 12),
  ('ECU13', 'Equador', 'E', 'team', 13),
  ('ECU14', 'Equador', 'E', 'team', 14),
  ('ECU15', 'Equador', 'E', 'team', 15),
  ('ECU16', 'Equador', 'E', 'team', 16),
  ('ECU17', 'Equador', 'E', 'team', 17),
  ('ECU18', 'Equador', 'E', 'team', 18),
  ('ECU19', 'Equador', 'E', 'team', 19),
  ('ECU20', 'Equador', 'E', 'team', 20),
  ('NED1', 'Holanda', 'F', 'team', 1),
  ('NED2', 'Holanda', 'F', 'team', 2),
  ('NED3', 'Holanda', 'F', 'team', 3),
  ('NED4', 'Holanda', 'F', 'team', 4),
  ('NED5', 'Holanda', 'F', 'team', 5),
  ('NED6', 'Holanda', 'F', 'team', 6),
  ('NED7', 'Holanda', 'F', 'team', 7),
  ('NED8', 'Holanda', 'F', 'team', 8),
  ('NED9', 'Holanda', 'F', 'team', 9),
  ('NED10', 'Holanda', 'F', 'team', 10),
  ('NED11', 'Holanda', 'F', 'team', 11),
  ('NED12', 'Holanda', 'F', 'team', 12),
  ('NED13', 'Holanda', 'F', 'team', 13),
  ('NED14', 'Holanda', 'F', 'team', 14),
  ('NED15', 'Holanda', 'F', 'team', 15),
  ('NED16', 'Holanda', 'F', 'team', 16),
  ('NED17', 'Holanda', 'F', 'team', 17),
  ('NED18', 'Holanda', 'F', 'team', 18),
  ('NED19', 'Holanda', 'F', 'team', 19),
  ('NED20', 'Holanda', 'F', 'team', 20),
  ('JPN1', 'Japão', 'F', 'team', 1),
  ('JPN2', 'Japão', 'F', 'team', 2),
  ('JPN3', 'Japão', 'F', 'team', 3),
  ('JPN4', 'Japão', 'F', 'team', 4),
  ('JPN5', 'Japão', 'F', 'team', 5),
  ('JPN6', 'Japão', 'F', 'team', 6),
  ('JPN7', 'Japão', 'F', 'team', 7),
  ('JPN8', 'Japão', 'F', 'team', 8),
  ('JPN9', 'Japão', 'F', 'team', 9),
  ('JPN10', 'Japão', 'F', 'team', 10),
  ('JPN11', 'Japão', 'F', 'team', 11),
  ('JPN12', 'Japão', 'F', 'team', 12),
  ('JPN13', 'Japão', 'F', 'team', 13),
  ('JPN14', 'Japão', 'F', 'team', 14),
  ('JPN15', 'Japão', 'F', 'team', 15),
  ('JPN16', 'Japão', 'F', 'team', 16),
  ('JPN17', 'Japão', 'F', 'team', 17),
  ('JPN18', 'Japão', 'F', 'team', 18),
  ('JPN19', 'Japão', 'F', 'team', 19),
  ('JPN20', 'Japão', 'F', 'team', 20),
  ('SWE1', 'Suécia', 'F', 'team', 1),
  ('SWE2', 'Suécia', 'F', 'team', 2),
  ('SWE3', 'Suécia', 'F', 'team', 3),
  ('SWE4', 'Suécia', 'F', 'team', 4),
  ('SWE5', 'Suécia', 'F', 'team', 5),
  ('SWE6', 'Suécia', 'F', 'team', 6),
  ('SWE7', 'Suécia', 'F', 'team', 7),
  ('SWE8', 'Suécia', 'F', 'team', 8),
  ('SWE9', 'Suécia', 'F', 'team', 9),
  ('SWE10', 'Suécia', 'F', 'team', 10),
  ('SWE11', 'Suécia', 'F', 'team', 11),
  ('SWE12', 'Suécia', 'F', 'team', 12),
  ('SWE13', 'Suécia', 'F', 'team', 13),
  ('SWE14', 'Suécia', 'F', 'team', 14),
  ('SWE15', 'Suécia', 'F', 'team', 15),
  ('SWE16', 'Suécia', 'F', 'team', 16),
  ('SWE17', 'Suécia', 'F', 'team', 17),
  ('SWE18', 'Suécia', 'F', 'team', 18),
  ('SWE19', 'Suécia', 'F', 'team', 19),
  ('SWE20', 'Suécia', 'F', 'team', 20),
  ('TUN1', 'Tunísia', 'F', 'team', 1),
  ('TUN2', 'Tunísia', 'F', 'team', 2),
  ('TUN3', 'Tunísia', 'F', 'team', 3),
  ('TUN4', 'Tunísia', 'F', 'team', 4),
  ('TUN5', 'Tunísia', 'F', 'team', 5),
  ('TUN6', 'Tunísia', 'F', 'team', 6),
  ('TUN7', 'Tunísia', 'F', 'team', 7),
  ('TUN8', 'Tunísia', 'F', 'team', 8),
  ('TUN9', 'Tunísia', 'F', 'team', 9),
  ('TUN10', 'Tunísia', 'F', 'team', 10),
  ('TUN11', 'Tunísia', 'F', 'team', 11),
  ('TUN12', 'Tunísia', 'F', 'team', 12),
  ('TUN13', 'Tunísia', 'F', 'team', 13),
  ('TUN14', 'Tunísia', 'F', 'team', 14),
  ('TUN15', 'Tunísia', 'F', 'team', 15),
  ('TUN16', 'Tunísia', 'F', 'team', 16),
  ('TUN17', 'Tunísia', 'F', 'team', 17),
  ('TUN18', 'Tunísia', 'F', 'team', 18),
  ('TUN19', 'Tunísia', 'F', 'team', 19),
  ('TUN20', 'Tunísia', 'F', 'team', 20),
  ('BEL1', 'Bélgica', 'G', 'team', 1),
  ('BEL2', 'Bélgica', 'G', 'team', 2),
  ('BEL3', 'Bélgica', 'G', 'team', 3),
  ('BEL4', 'Bélgica', 'G', 'team', 4),
  ('BEL5', 'Bélgica', 'G', 'team', 5),
  ('BEL6', 'Bélgica', 'G', 'team', 6),
  ('BEL7', 'Bélgica', 'G', 'team', 7),
  ('BEL8', 'Bélgica', 'G', 'team', 8),
  ('BEL9', 'Bélgica', 'G', 'team', 9),
  ('BEL10', 'Bélgica', 'G', 'team', 10),
  ('BEL11', 'Bélgica', 'G', 'team', 11),
  ('BEL12', 'Bélgica', 'G', 'team', 12),
  ('BEL13', 'Bélgica', 'G', 'team', 13),
  ('BEL14', 'Bélgica', 'G', 'team', 14),
  ('BEL15', 'Bélgica', 'G', 'team', 15),
  ('BEL16', 'Bélgica', 'G', 'team', 16),
  ('BEL17', 'Bélgica', 'G', 'team', 17),
  ('BEL18', 'Bélgica', 'G', 'team', 18),
  ('BEL19', 'Bélgica', 'G', 'team', 19),
  ('BEL20', 'Bélgica', 'G', 'team', 20),
  ('EGY1', 'Egito', 'G', 'team', 1),
  ('EGY2', 'Egito', 'G', 'team', 2),
  ('EGY3', 'Egito', 'G', 'team', 3),
  ('EGY4', 'Egito', 'G', 'team', 4),
  ('EGY5', 'Egito', 'G', 'team', 5),
  ('EGY6', 'Egito', 'G', 'team', 6),
  ('EGY7', 'Egito', 'G', 'team', 7),
  ('EGY8', 'Egito', 'G', 'team', 8),
  ('EGY9', 'Egito', 'G', 'team', 9),
  ('EGY10', 'Egito', 'G', 'team', 10),
  ('EGY11', 'Egito', 'G', 'team', 11),
  ('EGY12', 'Egito', 'G', 'team', 12),
  ('EGY13', 'Egito', 'G', 'team', 13),
  ('EGY14', 'Egito', 'G', 'team', 14),
  ('EGY15', 'Egito', 'G', 'team', 15),
  ('EGY16', 'Egito', 'G', 'team', 16),
  ('EGY17', 'Egito', 'G', 'team', 17),
  ('EGY18', 'Egito', 'G', 'team', 18),
  ('EGY19', 'Egito', 'G', 'team', 19),
  ('EGY20', 'Egito', 'G', 'team', 20),
  ('IRN1', 'Irã', 'G', 'team', 1),
  ('IRN2', 'Irã', 'G', 'team', 2),
  ('IRN3', 'Irã', 'G', 'team', 3),
  ('IRN4', 'Irã', 'G', 'team', 4),
  ('IRN5', 'Irã', 'G', 'team', 5),
  ('IRN6', 'Irã', 'G', 'team', 6),
  ('IRN7', 'Irã', 'G', 'team', 7),
  ('IRN8', 'Irã', 'G', 'team', 8),
  ('IRN9', 'Irã', 'G', 'team', 9),
  ('IRN10', 'Irã', 'G', 'team', 10),
  ('IRN11', 'Irã', 'G', 'team', 11),
  ('IRN12', 'Irã', 'G', 'team', 12),
  ('IRN13', 'Irã', 'G', 'team', 13),
  ('IRN14', 'Irã', 'G', 'team', 14),
  ('IRN15', 'Irã', 'G', 'team', 15),
  ('IRN16', 'Irã', 'G', 'team', 16),
  ('IRN17', 'Irã', 'G', 'team', 17),
  ('IRN18', 'Irã', 'G', 'team', 18),
  ('IRN19', 'Irã', 'G', 'team', 19),
  ('IRN20', 'Irã', 'G', 'team', 20),
  ('NZL1', 'Nova Zelândia', 'G', 'team', 1),
  ('NZL2', 'Nova Zelândia', 'G', 'team', 2),
  ('NZL3', 'Nova Zelândia', 'G', 'team', 3),
  ('NZL4', 'Nova Zelândia', 'G', 'team', 4),
  ('NZL5', 'Nova Zelândia', 'G', 'team', 5),
  ('NZL6', 'Nova Zelândia', 'G', 'team', 6),
  ('NZL7', 'Nova Zelândia', 'G', 'team', 7),
  ('NZL8', 'Nova Zelândia', 'G', 'team', 8),
  ('NZL9', 'Nova Zelândia', 'G', 'team', 9),
  ('NZL10', 'Nova Zelândia', 'G', 'team', 10),
  ('NZL11', 'Nova Zelândia', 'G', 'team', 11),
  ('NZL12', 'Nova Zelândia', 'G', 'team', 12),
  ('NZL13', 'Nova Zelândia', 'G', 'team', 13),
  ('NZL14', 'Nova Zelândia', 'G', 'team', 14),
  ('NZL15', 'Nova Zelândia', 'G', 'team', 15),
  ('NZL16', 'Nova Zelândia', 'G', 'team', 16),
  ('NZL17', 'Nova Zelândia', 'G', 'team', 17),
  ('NZL18', 'Nova Zelândia', 'G', 'team', 18),
  ('NZL19', 'Nova Zelândia', 'G', 'team', 19),
  ('NZL20', 'Nova Zelândia', 'G', 'team', 20),
  ('ESP1', 'Espanha', 'H', 'team', 1),
  ('ESP2', 'Espanha', 'H', 'team', 2),
  ('ESP3', 'Espanha', 'H', 'team', 3),
  ('ESP4', 'Espanha', 'H', 'team', 4),
  ('ESP5', 'Espanha', 'H', 'team', 5),
  ('ESP6', 'Espanha', 'H', 'team', 6),
  ('ESP7', 'Espanha', 'H', 'team', 7),
  ('ESP8', 'Espanha', 'H', 'team', 8),
  ('ESP9', 'Espanha', 'H', 'team', 9),
  ('ESP10', 'Espanha', 'H', 'team', 10),
  ('ESP11', 'Espanha', 'H', 'team', 11),
  ('ESP12', 'Espanha', 'H', 'team', 12),
  ('ESP13', 'Espanha', 'H', 'team', 13),
  ('ESP14', 'Espanha', 'H', 'team', 14),
  ('ESP15', 'Espanha', 'H', 'team', 15),
  ('ESP16', 'Espanha', 'H', 'team', 16),
  ('ESP17', 'Espanha', 'H', 'team', 17),
  ('ESP18', 'Espanha', 'H', 'team', 18),
  ('ESP19', 'Espanha', 'H', 'team', 19),
  ('ESP20', 'Espanha', 'H', 'team', 20),
  ('CPV1', 'Cabo Verde', 'H', 'team', 1),
  ('CPV2', 'Cabo Verde', 'H', 'team', 2),
  ('CPV3', 'Cabo Verde', 'H', 'team', 3),
  ('CPV4', 'Cabo Verde', 'H', 'team', 4),
  ('CPV5', 'Cabo Verde', 'H', 'team', 5),
  ('CPV6', 'Cabo Verde', 'H', 'team', 6),
  ('CPV7', 'Cabo Verde', 'H', 'team', 7),
  ('CPV8', 'Cabo Verde', 'H', 'team', 8),
  ('CPV9', 'Cabo Verde', 'H', 'team', 9),
  ('CPV10', 'Cabo Verde', 'H', 'team', 10),
  ('CPV11', 'Cabo Verde', 'H', 'team', 11),
  ('CPV12', 'Cabo Verde', 'H', 'team', 12),
  ('CPV13', 'Cabo Verde', 'H', 'team', 13),
  ('CPV14', 'Cabo Verde', 'H', 'team', 14),
  ('CPV15', 'Cabo Verde', 'H', 'team', 15),
  ('CPV16', 'Cabo Verde', 'H', 'team', 16),
  ('CPV17', 'Cabo Verde', 'H', 'team', 17),
  ('CPV18', 'Cabo Verde', 'H', 'team', 18),
  ('CPV19', 'Cabo Verde', 'H', 'team', 19),
  ('CPV20', 'Cabo Verde', 'H', 'team', 20),
  ('KSA1', 'Arábia Saudita', 'H', 'team', 1),
  ('KSA2', 'Arábia Saudita', 'H', 'team', 2),
  ('KSA3', 'Arábia Saudita', 'H', 'team', 3),
  ('KSA4', 'Arábia Saudita', 'H', 'team', 4),
  ('KSA5', 'Arábia Saudita', 'H', 'team', 5),
  ('KSA6', 'Arábia Saudita', 'H', 'team', 6),
  ('KSA7', 'Arábia Saudita', 'H', 'team', 7),
  ('KSA8', 'Arábia Saudita', 'H', 'team', 8),
  ('KSA9', 'Arábia Saudita', 'H', 'team', 9),
  ('KSA10', 'Arábia Saudita', 'H', 'team', 10),
  ('KSA11', 'Arábia Saudita', 'H', 'team', 11),
  ('KSA12', 'Arábia Saudita', 'H', 'team', 12),
  ('KSA13', 'Arábia Saudita', 'H', 'team', 13),
  ('KSA14', 'Arábia Saudita', 'H', 'team', 14),
  ('KSA15', 'Arábia Saudita', 'H', 'team', 15),
  ('KSA16', 'Arábia Saudita', 'H', 'team', 16),
  ('KSA17', 'Arábia Saudita', 'H', 'team', 17),
  ('KSA18', 'Arábia Saudita', 'H', 'team', 18),
  ('KSA19', 'Arábia Saudita', 'H', 'team', 19),
  ('KSA20', 'Arábia Saudita', 'H', 'team', 20),
  ('URU1', 'Uruguai', 'H', 'team', 1),
  ('URU2', 'Uruguai', 'H', 'team', 2),
  ('URU3', 'Uruguai', 'H', 'team', 3),
  ('URU4', 'Uruguai', 'H', 'team', 4),
  ('URU5', 'Uruguai', 'H', 'team', 5),
  ('URU6', 'Uruguai', 'H', 'team', 6),
  ('URU7', 'Uruguai', 'H', 'team', 7),
  ('URU8', 'Uruguai', 'H', 'team', 8),
  ('URU9', 'Uruguai', 'H', 'team', 9),
  ('URU10', 'Uruguai', 'H', 'team', 10),
  ('URU11', 'Uruguai', 'H', 'team', 11),
  ('URU12', 'Uruguai', 'H', 'team', 12),
  ('URU13', 'Uruguai', 'H', 'team', 13),
  ('URU14', 'Uruguai', 'H', 'team', 14),
  ('URU15', 'Uruguai', 'H', 'team', 15),
  ('URU16', 'Uruguai', 'H', 'team', 16),
  ('URU17', 'Uruguai', 'H', 'team', 17),
  ('URU18', 'Uruguai', 'H', 'team', 18),
  ('URU19', 'Uruguai', 'H', 'team', 19),
  ('URU20', 'Uruguai', 'H', 'team', 20),
  ('FRA1', 'França', 'I', 'team', 1),
  ('FRA2', 'França', 'I', 'team', 2),
  ('FRA3', 'França', 'I', 'team', 3),
  ('FRA4', 'França', 'I', 'team', 4),
  ('FRA5', 'França', 'I', 'team', 5),
  ('FRA6', 'França', 'I', 'team', 6),
  ('FRA7', 'França', 'I', 'team', 7),
  ('FRA8', 'França', 'I', 'team', 8),
  ('FRA9', 'França', 'I', 'team', 9),
  ('FRA10', 'França', 'I', 'team', 10),
  ('FRA11', 'França', 'I', 'team', 11),
  ('FRA12', 'França', 'I', 'team', 12),
  ('FRA13', 'França', 'I', 'team', 13),
  ('FRA14', 'França', 'I', 'team', 14),
  ('FRA15', 'França', 'I', 'team', 15),
  ('FRA16', 'França', 'I', 'team', 16),
  ('FRA17', 'França', 'I', 'team', 17),
  ('FRA18', 'França', 'I', 'team', 18),
  ('FRA19', 'França', 'I', 'team', 19),
  ('FRA20', 'França', 'I', 'team', 20),
  ('SEN1', 'Senegal', 'I', 'team', 1),
  ('SEN2', 'Senegal', 'I', 'team', 2),
  ('SEN3', 'Senegal', 'I', 'team', 3),
  ('SEN4', 'Senegal', 'I', 'team', 4),
  ('SEN5', 'Senegal', 'I', 'team', 5),
  ('SEN6', 'Senegal', 'I', 'team', 6),
  ('SEN7', 'Senegal', 'I', 'team', 7),
  ('SEN8', 'Senegal', 'I', 'team', 8),
  ('SEN9', 'Senegal', 'I', 'team', 9),
  ('SEN10', 'Senegal', 'I', 'team', 10),
  ('SEN11', 'Senegal', 'I', 'team', 11),
  ('SEN12', 'Senegal', 'I', 'team', 12),
  ('SEN13', 'Senegal', 'I', 'team', 13),
  ('SEN14', 'Senegal', 'I', 'team', 14),
  ('SEN15', 'Senegal', 'I', 'team', 15),
  ('SEN16', 'Senegal', 'I', 'team', 16),
  ('SEN17', 'Senegal', 'I', 'team', 17),
  ('SEN18', 'Senegal', 'I', 'team', 18),
  ('SEN19', 'Senegal', 'I', 'team', 19),
  ('SEN20', 'Senegal', 'I', 'team', 20),
  ('IRQ1', 'Iraque', 'I', 'team', 1),
  ('IRQ2', 'Iraque', 'I', 'team', 2),
  ('IRQ3', 'Iraque', 'I', 'team', 3),
  ('IRQ4', 'Iraque', 'I', 'team', 4),
  ('IRQ5', 'Iraque', 'I', 'team', 5),
  ('IRQ6', 'Iraque', 'I', 'team', 6),
  ('IRQ7', 'Iraque', 'I', 'team', 7),
  ('IRQ8', 'Iraque', 'I', 'team', 8),
  ('IRQ9', 'Iraque', 'I', 'team', 9),
  ('IRQ10', 'Iraque', 'I', 'team', 10),
  ('IRQ11', 'Iraque', 'I', 'team', 11),
  ('IRQ12', 'Iraque', 'I', 'team', 12),
  ('IRQ13', 'Iraque', 'I', 'team', 13),
  ('IRQ14', 'Iraque', 'I', 'team', 14),
  ('IRQ15', 'Iraque', 'I', 'team', 15),
  ('IRQ16', 'Iraque', 'I', 'team', 16),
  ('IRQ17', 'Iraque', 'I', 'team', 17),
  ('IRQ18', 'Iraque', 'I', 'team', 18),
  ('IRQ19', 'Iraque', 'I', 'team', 19),
  ('IRQ20', 'Iraque', 'I', 'team', 20),
  ('NOR1', 'Noruega', 'I', 'team', 1),
  ('NOR2', 'Noruega', 'I', 'team', 2),
  ('NOR3', 'Noruega', 'I', 'team', 3),
  ('NOR4', 'Noruega', 'I', 'team', 4),
  ('NOR5', 'Noruega', 'I', 'team', 5),
  ('NOR6', 'Noruega', 'I', 'team', 6),
  ('NOR7', 'Noruega', 'I', 'team', 7),
  ('NOR8', 'Noruega', 'I', 'team', 8),
  ('NOR9', 'Noruega', 'I', 'team', 9),
  ('NOR10', 'Noruega', 'I', 'team', 10),
  ('NOR11', 'Noruega', 'I', 'team', 11),
  ('NOR12', 'Noruega', 'I', 'team', 12),
  ('NOR13', 'Noruega', 'I', 'team', 13),
  ('NOR14', 'Noruega', 'I', 'team', 14),
  ('NOR15', 'Noruega', 'I', 'team', 15),
  ('NOR16', 'Noruega', 'I', 'team', 16),
  ('NOR17', 'Noruega', 'I', 'team', 17),
  ('NOR18', 'Noruega', 'I', 'team', 18),
  ('NOR19', 'Noruega', 'I', 'team', 19),
  ('NOR20', 'Noruega', 'I', 'team', 20),
  ('ARG1', 'Argentina', 'J', 'team', 1),
  ('ARG2', 'Argentina', 'J', 'team', 2),
  ('ARG3', 'Argentina', 'J', 'team', 3),
  ('ARG4', 'Argentina', 'J', 'team', 4),
  ('ARG5', 'Argentina', 'J', 'team', 5),
  ('ARG6', 'Argentina', 'J', 'team', 6),
  ('ARG7', 'Argentina', 'J', 'team', 7),
  ('ARG8', 'Argentina', 'J', 'team', 8),
  ('ARG9', 'Argentina', 'J', 'team', 9),
  ('ARG10', 'Argentina', 'J', 'team', 10),
  ('ARG11', 'Argentina', 'J', 'team', 11),
  ('ARG12', 'Argentina', 'J', 'team', 12),
  ('ARG13', 'Argentina', 'J', 'team', 13),
  ('ARG14', 'Argentina', 'J', 'team', 14),
  ('ARG15', 'Argentina', 'J', 'team', 15),
  ('ARG16', 'Argentina', 'J', 'team', 16),
  ('ARG17', 'Argentina', 'J', 'team', 17),
  ('ARG18', 'Argentina', 'J', 'team', 18),
  ('ARG19', 'Argentina', 'J', 'team', 19),
  ('ARG20', 'Argentina', 'J', 'team', 20),
  ('ALG1', 'Argélia', 'J', 'team', 1),
  ('ALG2', 'Argélia', 'J', 'team', 2),
  ('ALG3', 'Argélia', 'J', 'team', 3),
  ('ALG4', 'Argélia', 'J', 'team', 4),
  ('ALG5', 'Argélia', 'J', 'team', 5),
  ('ALG6', 'Argélia', 'J', 'team', 6),
  ('ALG7', 'Argélia', 'J', 'team', 7),
  ('ALG8', 'Argélia', 'J', 'team', 8),
  ('ALG9', 'Argélia', 'J', 'team', 9),
  ('ALG10', 'Argélia', 'J', 'team', 10),
  ('ALG11', 'Argélia', 'J', 'team', 11),
  ('ALG12', 'Argélia', 'J', 'team', 12),
  ('ALG13', 'Argélia', 'J', 'team', 13),
  ('ALG14', 'Argélia', 'J', 'team', 14),
  ('ALG15', 'Argélia', 'J', 'team', 15),
  ('ALG16', 'Argélia', 'J', 'team', 16),
  ('ALG17', 'Argélia', 'J', 'team', 17),
  ('ALG18', 'Argélia', 'J', 'team', 18),
  ('ALG19', 'Argélia', 'J', 'team', 19),
  ('ALG20', 'Argélia', 'J', 'team', 20),
  ('AUT1', 'Áustria', 'J', 'team', 1),
  ('AUT2', 'Áustria', 'J', 'team', 2),
  ('AUT3', 'Áustria', 'J', 'team', 3),
  ('AUT4', 'Áustria', 'J', 'team', 4),
  ('AUT5', 'Áustria', 'J', 'team', 5),
  ('AUT6', 'Áustria', 'J', 'team', 6),
  ('AUT7', 'Áustria', 'J', 'team', 7),
  ('AUT8', 'Áustria', 'J', 'team', 8),
  ('AUT9', 'Áustria', 'J', 'team', 9),
  ('AUT10', 'Áustria', 'J', 'team', 10),
  ('AUT11', 'Áustria', 'J', 'team', 11),
  ('AUT12', 'Áustria', 'J', 'team', 12),
  ('AUT13', 'Áustria', 'J', 'team', 13),
  ('AUT14', 'Áustria', 'J', 'team', 14),
  ('AUT15', 'Áustria', 'J', 'team', 15),
  ('AUT16', 'Áustria', 'J', 'team', 16),
  ('AUT17', 'Áustria', 'J', 'team', 17),
  ('AUT18', 'Áustria', 'J', 'team', 18),
  ('AUT19', 'Áustria', 'J', 'team', 19),
  ('AUT20', 'Áustria', 'J', 'team', 20),
  ('JOR1', 'Jordânia', 'J', 'team', 1),
  ('JOR2', 'Jordânia', 'J', 'team', 2),
  ('JOR3', 'Jordânia', 'J', 'team', 3),
  ('JOR4', 'Jordânia', 'J', 'team', 4),
  ('JOR5', 'Jordânia', 'J', 'team', 5),
  ('JOR6', 'Jordânia', 'J', 'team', 6),
  ('JOR7', 'Jordânia', 'J', 'team', 7),
  ('JOR8', 'Jordânia', 'J', 'team', 8),
  ('JOR9', 'Jordânia', 'J', 'team', 9),
  ('JOR10', 'Jordânia', 'J', 'team', 10),
  ('JOR11', 'Jordânia', 'J', 'team', 11),
  ('JOR12', 'Jordânia', 'J', 'team', 12),
  ('JOR13', 'Jordânia', 'J', 'team', 13),
  ('JOR14', 'Jordânia', 'J', 'team', 14),
  ('JOR15', 'Jordânia', 'J', 'team', 15),
  ('JOR16', 'Jordânia', 'J', 'team', 16),
  ('JOR17', 'Jordânia', 'J', 'team', 17),
  ('JOR18', 'Jordânia', 'J', 'team', 18),
  ('JOR19', 'Jordânia', 'J', 'team', 19),
  ('JOR20', 'Jordânia', 'J', 'team', 20),
  ('POR1', 'Portugal', 'K', 'team', 1),
  ('POR2', 'Portugal', 'K', 'team', 2),
  ('POR3', 'Portugal', 'K', 'team', 3),
  ('POR4', 'Portugal', 'K', 'team', 4),
  ('POR5', 'Portugal', 'K', 'team', 5),
  ('POR6', 'Portugal', 'K', 'team', 6),
  ('POR7', 'Portugal', 'K', 'team', 7),
  ('POR8', 'Portugal', 'K', 'team', 8),
  ('POR9', 'Portugal', 'K', 'team', 9),
  ('POR10', 'Portugal', 'K', 'team', 10),
  ('POR11', 'Portugal', 'K', 'team', 11),
  ('POR12', 'Portugal', 'K', 'team', 12),
  ('POR13', 'Portugal', 'K', 'team', 13),
  ('POR14', 'Portugal', 'K', 'team', 14),
  ('POR15', 'Portugal', 'K', 'team', 15),
  ('POR16', 'Portugal', 'K', 'team', 16),
  ('POR17', 'Portugal', 'K', 'team', 17),
  ('POR18', 'Portugal', 'K', 'team', 18),
  ('POR19', 'Portugal', 'K', 'team', 19),
  ('POR20', 'Portugal', 'K', 'team', 20),
  ('COD1', 'Congo', 'K', 'team', 1),
  ('COD2', 'Congo', 'K', 'team', 2),
  ('COD3', 'Congo', 'K', 'team', 3),
  ('COD4', 'Congo', 'K', 'team', 4),
  ('COD5', 'Congo', 'K', 'team', 5),
  ('COD6', 'Congo', 'K', 'team', 6),
  ('COD7', 'Congo', 'K', 'team', 7),
  ('COD8', 'Congo', 'K', 'team', 8),
  ('COD9', 'Congo', 'K', 'team', 9),
  ('COD10', 'Congo', 'K', 'team', 10),
  ('COD11', 'Congo', 'K', 'team', 11),
  ('COD12', 'Congo', 'K', 'team', 12),
  ('COD13', 'Congo', 'K', 'team', 13),
  ('COD14', 'Congo', 'K', 'team', 14),
  ('COD15', 'Congo', 'K', 'team', 15),
  ('COD16', 'Congo', 'K', 'team', 16),
  ('COD17', 'Congo', 'K', 'team', 17),
  ('COD18', 'Congo', 'K', 'team', 18),
  ('COD19', 'Congo', 'K', 'team', 19),
  ('COD20', 'Congo', 'K', 'team', 20),
  ('UZB1', 'Uzbequistão', 'K', 'team', 1),
  ('UZB2', 'Uzbequistão', 'K', 'team', 2),
  ('UZB3', 'Uzbequistão', 'K', 'team', 3),
  ('UZB4', 'Uzbequistão', 'K', 'team', 4),
  ('UZB5', 'Uzbequistão', 'K', 'team', 5),
  ('UZB6', 'Uzbequistão', 'K', 'team', 6),
  ('UZB7', 'Uzbequistão', 'K', 'team', 7),
  ('UZB8', 'Uzbequistão', 'K', 'team', 8),
  ('UZB9', 'Uzbequistão', 'K', 'team', 9),
  ('UZB10', 'Uzbequistão', 'K', 'team', 10),
  ('UZB11', 'Uzbequistão', 'K', 'team', 11),
  ('UZB12', 'Uzbequistão', 'K', 'team', 12),
  ('UZB13', 'Uzbequistão', 'K', 'team', 13),
  ('UZB14', 'Uzbequistão', 'K', 'team', 14),
  ('UZB15', 'Uzbequistão', 'K', 'team', 15),
  ('UZB16', 'Uzbequistão', 'K', 'team', 16),
  ('UZB17', 'Uzbequistão', 'K', 'team', 17),
  ('UZB18', 'Uzbequistão', 'K', 'team', 18),
  ('UZB19', 'Uzbequistão', 'K', 'team', 19),
  ('UZB20', 'Uzbequistão', 'K', 'team', 20),
  ('COL1', 'Colômbia', 'K', 'team', 1),
  ('COL2', 'Colômbia', 'K', 'team', 2),
  ('COL3', 'Colômbia', 'K', 'team', 3),
  ('COL4', 'Colômbia', 'K', 'team', 4),
  ('COL5', 'Colômbia', 'K', 'team', 5),
  ('COL6', 'Colômbia', 'K', 'team', 6),
  ('COL7', 'Colômbia', 'K', 'team', 7),
  ('COL8', 'Colômbia', 'K', 'team', 8),
  ('COL9', 'Colômbia', 'K', 'team', 9),
  ('COL10', 'Colômbia', 'K', 'team', 10),
  ('COL11', 'Colômbia', 'K', 'team', 11),
  ('COL12', 'Colômbia', 'K', 'team', 12),
  ('COL13', 'Colômbia', 'K', 'team', 13),
  ('COL14', 'Colômbia', 'K', 'team', 14),
  ('COL15', 'Colômbia', 'K', 'team', 15),
  ('COL16', 'Colômbia', 'K', 'team', 16),
  ('COL17', 'Colômbia', 'K', 'team', 17),
  ('COL18', 'Colômbia', 'K', 'team', 18),
  ('COL19', 'Colômbia', 'K', 'team', 19),
  ('COL20', 'Colômbia', 'K', 'team', 20),
  ('ENG1', 'Inglaterra', 'L', 'team', 1),
  ('ENG2', 'Inglaterra', 'L', 'team', 2),
  ('ENG3', 'Inglaterra', 'L', 'team', 3),
  ('ENG4', 'Inglaterra', 'L', 'team', 4),
  ('ENG5', 'Inglaterra', 'L', 'team', 5),
  ('ENG6', 'Inglaterra', 'L', 'team', 6),
  ('ENG7', 'Inglaterra', 'L', 'team', 7),
  ('ENG8', 'Inglaterra', 'L', 'team', 8),
  ('ENG9', 'Inglaterra', 'L', 'team', 9),
  ('ENG10', 'Inglaterra', 'L', 'team', 10),
  ('ENG11', 'Inglaterra', 'L', 'team', 11),
  ('ENG12', 'Inglaterra', 'L', 'team', 12),
  ('ENG13', 'Inglaterra', 'L', 'team', 13),
  ('ENG14', 'Inglaterra', 'L', 'team', 14),
  ('ENG15', 'Inglaterra', 'L', 'team', 15),
  ('ENG16', 'Inglaterra', 'L', 'team', 16),
  ('ENG17', 'Inglaterra', 'L', 'team', 17),
  ('ENG18', 'Inglaterra', 'L', 'team', 18),
  ('ENG19', 'Inglaterra', 'L', 'team', 19),
  ('ENG20', 'Inglaterra', 'L', 'team', 20),
  ('CRO1', 'Croácia', 'L', 'team', 1),
  ('CRO2', 'Croácia', 'L', 'team', 2),
  ('CRO3', 'Croácia', 'L', 'team', 3),
  ('CRO4', 'Croácia', 'L', 'team', 4),
  ('CRO5', 'Croácia', 'L', 'team', 5),
  ('CRO6', 'Croácia', 'L', 'team', 6),
  ('CRO7', 'Croácia', 'L', 'team', 7),
  ('CRO8', 'Croácia', 'L', 'team', 8),
  ('CRO9', 'Croácia', 'L', 'team', 9),
  ('CRO10', 'Croácia', 'L', 'team', 10),
  ('CRO11', 'Croácia', 'L', 'team', 11),
  ('CRO12', 'Croácia', 'L', 'team', 12),
  ('CRO13', 'Croácia', 'L', 'team', 13),
  ('CRO14', 'Croácia', 'L', 'team', 14),
  ('CRO15', 'Croácia', 'L', 'team', 15),
  ('CRO16', 'Croácia', 'L', 'team', 16),
  ('CRO17', 'Croácia', 'L', 'team', 17),
  ('CRO18', 'Croácia', 'L', 'team', 18),
  ('CRO19', 'Croácia', 'L', 'team', 19),
  ('CRO20', 'Croácia', 'L', 'team', 20),
  ('GHA1', 'Gana', 'L', 'team', 1),
  ('GHA2', 'Gana', 'L', 'team', 2),
  ('GHA3', 'Gana', 'L', 'team', 3),
  ('GHA4', 'Gana', 'L', 'team', 4),
  ('GHA5', 'Gana', 'L', 'team', 5),
  ('GHA6', 'Gana', 'L', 'team', 6),
  ('GHA7', 'Gana', 'L', 'team', 7),
  ('GHA8', 'Gana', 'L', 'team', 8),
  ('GHA9', 'Gana', 'L', 'team', 9),
  ('GHA10', 'Gana', 'L', 'team', 10),
  ('GHA11', 'Gana', 'L', 'team', 11),
  ('GHA12', 'Gana', 'L', 'team', 12),
  ('GHA13', 'Gana', 'L', 'team', 13),
  ('GHA14', 'Gana', 'L', 'team', 14),
  ('GHA15', 'Gana', 'L', 'team', 15),
  ('GHA16', 'Gana', 'L', 'team', 16),
  ('GHA17', 'Gana', 'L', 'team', 17),
  ('GHA18', 'Gana', 'L', 'team', 18),
  ('GHA19', 'Gana', 'L', 'team', 19),
  ('GHA20', 'Gana', 'L', 'team', 20),
  ('PAN1', 'Panamá', 'L', 'team', 1),
  ('PAN2', 'Panamá', 'L', 'team', 2),
  ('PAN3', 'Panamá', 'L', 'team', 3),
  ('PAN4', 'Panamá', 'L', 'team', 4),
  ('PAN5', 'Panamá', 'L', 'team', 5),
  ('PAN6', 'Panamá', 'L', 'team', 6),
  ('PAN7', 'Panamá', 'L', 'team', 7),
  ('PAN8', 'Panamá', 'L', 'team', 8),
  ('PAN9', 'Panamá', 'L', 'team', 9),
  ('PAN10', 'Panamá', 'L', 'team', 10),
  ('PAN11', 'Panamá', 'L', 'team', 11),
  ('PAN12', 'Panamá', 'L', 'team', 12),
  ('PAN13', 'Panamá', 'L', 'team', 13),
  ('PAN14', 'Panamá', 'L', 'team', 14),
  ('PAN15', 'Panamá', 'L', 'team', 15),
  ('PAN16', 'Panamá', 'L', 'team', 16),
  ('PAN17', 'Panamá', 'L', 'team', 17),
  ('PAN18', 'Panamá', 'L', 'team', 18),
  ('PAN19', 'Panamá', 'L', 'team', 19),
  ('PAN20', 'Panamá', 'L', 'team', 20),
  ('00', 'Fifa World Cup History', 'ESP', 'special', 1),
  ('FWC1', 'Fifa World Cup History', 'ESP', 'special', 2),
  ('FWC2', 'Fifa World Cup History', 'ESP', 'special', 3),
  ('FWC3', 'Fifa World Cup History', 'ESP', 'special', 4),
  ('FWC4', 'Fifa World Cup History', 'ESP', 'special', 5),
  ('FWC5', 'Fifa World Cup History', 'ESP', 'special', 6),
  ('FWC6', 'Fifa World Cup History', 'ESP', 'special', 7),
  ('FWC7', 'Fifa World Cup History', 'ESP', 'special', 8),
  ('FWC8', 'Fifa World Cup History', 'ESP', 'special', 9),
  ('FWC9', 'Fifa World Cup History', 'ESP', 'special', 10),
  ('FWC10', 'Fifa World Cup History', 'ESP', 'special', 11),
  ('FWC11', 'Fifa World Cup History', 'ESP', 'special', 12),
  ('FWC12', 'Fifa World Cup History', 'ESP', 'special', 13),
  ('FWC13', 'Fifa World Cup History', 'ESP', 'special', 14),
  ('FWC14', 'Fifa World Cup History', 'ESP', 'special', 15),
  ('FWC15', 'Fifa World Cup History', 'ESP', 'special', 16),
  ('FWC16', 'Fifa World Cup History', 'ESP', 'special', 17),
  ('FWC17', 'Fifa World Cup History', 'ESP', 'special', 18),
  ('FWC18', 'Fifa World Cup History', 'ESP', 'special', 19),
  ('FWC19', 'Fifa World Cup History', 'ESP', 'special', 20),
  ('CC1', 'Coca-Cola', 'CC', 'coke', 1),
  ('CC2', 'Coca-Cola', 'CC', 'coke', 2),
  ('CC3', 'Coca-Cola', 'CC', 'coke', 3),
  ('CC4', 'Coca-Cola', 'CC', 'coke', 4),
  ('CC5', 'Coca-Cola', 'CC', 'coke', 5),
  ('CC6', 'Coca-Cola', 'CC', 'coke', 6),
  ('CC7', 'Coca-Cola', 'CC', 'coke', 7),
  ('CC8', 'Coca-Cola', 'CC', 'coke', 8),
  ('CC9', 'Coca-Cola', 'CC', 'coke', 9),
  ('CC10', 'Coca-Cola', 'CC', 'coke', 10),
  ('CC11', 'Coca-Cola', 'CC', 'coke', 11),
  ('CC12', 'Coca-Cola', 'CC', 'coke', 12),
  ('CC13', 'Coca-Cola', 'CC', 'coke', 13),
  ('CC14', 'Coca-Cola', 'CC', 'coke', 14)
on conflict (code) do nothing;
